// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaM6lUqgR8AX2XH1ME2D7HwBzQXqV0Lv0',
    appId: '1:90511765723:web:922feef108593931d89cfe',
    messagingSenderId: '90511765723',
    projectId: 'artho-ojol',
    authDomain: 'artho-ojol.firebaseapp.com',
    storageBucket: 'artho-ojol.appspot.com',
    measurementId: 'G-J1WRK3ZR38',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsXXH83oLl9l6lEgE_iNefOErV36E7jio',
    appId: '1:90511765723:android:f27d538a1b4566c1d89cfe',
    messagingSenderId: '90511765723',
    projectId: 'artho-ojol',
    storageBucket: 'artho-ojol.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvC2rabSg-9fgyTCHUjlmx24HCixcVzy4',
    appId: '1:90511765723:ios:b63c4a0174bf27f0d89cfe',
    messagingSenderId: '90511765723',
    projectId: 'artho-ojol',
    storageBucket: 'artho-ojol.appspot.com',
    iosClientId: '90511765723-3t47mhcoaq33b13k32e5iomv69bv07i3.apps.googleusercontent.com',
    iosBundleId: 'id.artho.customer',
  );
}
